### ISSUE TITLE
adding monitor sometimes crashes

### ISSUE THREAD

**Issue by os-nicolas** [DeepwaterCreations/nomogaia-catalogue#33]
Happens reliably after you add a new row and add a monitor without adding data to the new row.

stack trace:

TypeError: Cannot read property 'replace' of null
    at getColumnHeadID (file:///C:/Users/Colin/Documents/Visual%20Studio%202015/Projects/WebSite1/nomogaia-catalogue/nomogaia-catalogue/test/MatrixUI.js:152:47)
    at file:///C:/Users/Colin/Documents/Visual%20Studio%202015/Projects/WebSite1/nomogaia-catalogue/nomogaia-catalogue/test/MatrixUI.js:42:90
    at Array.forEach (native)
    at Matrix.rebuild (file:///C:/Users/Colin/Documents/Visual%20Studio%202015/Projects/WebSite1/nomogaia-catalogue/nomogaia-catalogue/test/MatrixUI.js:41:61)
    at file:///C:/Users/Colin/Documents/Visual%20Studio%202015/Projects/WebSite1/nomogaia-catalogue/nomogaia-catalogue/test/MatrixUI.js:133:18
    at file:///C:/Users/Colin/Documents/Visual%20Studio%202015/Projects/WebSite1/nomogaia-catalogue/nomogaia-catalogue/test/MonitorTabsUI.js:76:13
    at Array.forEach (native)
    at MonitorTabs.addTab (file:///C:/Users/Colin/Documents/Visual%20Studio%202015/Projects/WebSite1/nomogaia-catalogue/nomogaia-catalogue/test/MonitorTabsUI.js:75:29)
    at MonitorTabs.addTabCallback (file:///C:/Users/Colin/Documents/Visual%20Studio%202015/Projects/WebSite1/nomogaia-catalogue/nomogaia-catalogue/test/MonitorTabsUI.js:84:25)
    at HTMLDivElement.MonitorTabs.$.dialog.buttons.click (file:///C:/Users/Colin/Documents/Visual%20Studio%202015/Projects/WebSite1/nomogaia-catalogue/nomogaia-catalogue/test/MonitorTabsUI.js:54:33)

**Comment by DeepwaterCreations** [comment]
The problem is that it's expecting to have a string for its column head. When the "string" goes to getColumnHeadID, it calls the replace method on it without bothering to check if it's actually a string or not.
Since the new row has no data, however, there is no string, and the method is undefined for that data.
I think getColumnHeadID works just fine. We don't want to check for a string, we want it to break if we passed it something we thought was a string but wasn't. MatrixUI - and probably ImpactedRights, also - should make sure they have actual data before doing anything with the data.

**Comment by DeepwaterCreations** [comment]
Basically caused by #28.

**Comment by DeepwaterCreations** [comment]
So I guess what I'm doing is, I'm putting in goofy filler values for the matrix. If we see those, we know we have an undefined right or rights-holder in the catalog's data.
This does not fix the underlying problem, which is that we can have undefined rights and rights-holders in the catalog's data.

**Comment by DeepwaterCreations** [comment]
TableData.getRows() does a silly thing, which is that it checks if its arguments are defined, but defines its return value array only in the case where they are.
So if they are not, it returns null and things break anyway.
I'm fixing this and tossing in a console warning for good measure.

**Comment by DeepwaterCreations** [comment]
Fixed, sort of. The underlying problem remains: Adding a new row needs to behave more sensibly!
