### ISSUE TITLE
File Loading doesn't load all the rows

### ISSUE THREAD

**Issue by DeepwaterCreations** [DeepwaterCreations/nomogaia-catalogue#92]
Or perhaps file saving doesn't save them?
Not sure exactly how to reproduce from scratch, but my matrixtest file displays the issue.

**Comment by DeepwaterCreations** [comment]
Something's changed - now when I load that file, I get:

TypeError: undefined is not a function
    at getCell (file:///E:/ColdThings/Nomogaia/test/ImpactedRights.js:65:73)
    at file:///E:/ColdThings/Nomogaia/test/ImpactedRights.js:182:74
    at Array.forEach (native)
    at rebuildImpactedRights (file:///E:/ColdThings/Nomogaia/test/ImpactedRights.js:171:20)
    at changeIRMonitorTabEvent (file:///E:/ColdThings/Nomogaia/test/ImpactedRights.js:72:9)
    at file:///E:/ColdThings/Nomogaia/test/MonitorTabsUI.js:49:13
    at Array.forEach (native)
    at MonitorTabs.changeToTab (file:///E:/ColdThings/Nomogaia/test/MonitorTabsUI.js:48:32)
    at HTMLDivElement.$.tabs.activate (file:///E:/ColdThings/Nomogaia/test/MonitorTabsUI.js:121:22)
    at e.Widget._trigger (file:///E:/ColdThings/Nomogaia/test/jquery-ui/jquery-ui.min.js:7:14974)

**Comment by DeepwaterCreations** [comment]
Looks like maybe it's filtering out all the rows and then trying to call methods on them...?

**Comment by DeepwaterCreations** [comment]
Not exactly. This is data cells that have "-" but are nevertheless being rounded to 2 decimal places.

**Comment by DeepwaterCreations** [comment]
Added a typeof check.
There appears to be a problem with matrixTest where it won't load all the way, but I'm chalking that up to it being from an older version of the program.
